[features]
seeds = false
skip-lint = false
[programs.devnet]
tiny_adventure = "8YQ15XxAekDQ2xtD7sYdmMzWne3XiDWm6JfhMRC2PmPg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/pier/solana/hk.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
